# Generated by Django 3.1.1 on 2020-10-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_prayer_category'),
        ('accounts', '0004_auto_20201004_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='praying',
            field=models.ManyToManyField(blank=True, limit_choices_to=10, to='main.Prayer'),
        ),
    ]
