# Generated by Django 3.1.1 on 2020-10-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_prayer_category'),
        ('accounts', '0005_profile_praying'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='praying',
            field=models.ManyToManyField(blank=True, to='main.Prayer'),
        ),
    ]
