# Generated by Django 3.1.1 on 2020-10-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayer',
            name='category',
            field=models.CharField(choices=[('a', 'salud'), ('b', 'familia'), ('c', 'espiritualidad'), ('e', 'economia'), ('d', 'otro')], default='a', max_length=1, null=True),
        ),
    ]
